version: '3.5'

services:
  book_db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: 'book_service'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'user'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'password'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      # <Port exposed> : <MySQL Port running inside container>
      - '3306:3306'
    expose:
      # Opens port 3306 on the container
      - '3306'
    # Where our data will be persisted
    volumes:
      - book-db:/var/lib/mysql

  stock_db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: 'stock_service'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'user'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'password'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      # <Port exposed> : <MySQL Port running inside container>
      - '3307:3306'
    expose:
      # Opens port 3306 on the container
      - '3306'
    # Where our data will be persisted
    volumes:
      - stock-db:/var/lib/mysql

  

# Names our volume
volumes:
  book-db:
  stock-db: